# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-18 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import openedx.core.djangoapps.xmodule_django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uninersity2035Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', openedx.core.djangoapps.xmodule_django.models.CourseKeyField(db_index=True, max_length=255, unique=True, verbose_name='Course ID')),
                ('unti2035_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
